import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ListOfSteps } from "@/components/list-of-steps";
import { Suspense } from "react";
import { Loading } from "@/components/loading";

const ubuntuRegular = localFont({
  src: "../assets/fonts/Ubuntu-Regular.ttf",
  variable: "--font-Ubuntu-Regular",
  weight: "400",
});
const ubuntuMedium = localFont({
  src: "../assets/fonts/Ubuntu-Medium.ttf",
  variable: "--font-Ubuntu-Medium",
  weight: "500",
});
const ubuntuBold = localFont({
  src: "../assets/fonts/Ubuntu-Bold.ttf",
  variable: "--font-Ubuntu-Bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Frontend Mentor | Multi-step form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntuRegular.variable} ${ubuntuMedium.variable} ${ubuntuBold.variable} antialiased bg-slate-200 flex justify-center items-center h-dvh`}>
        <Suspense fallback={<Loading />}>
          <main className="w-full flex bg-zinc-50 h-[540px] max-w-4xl p-4 font-[family-name:var(--font-Ubuntu-Regular)] rounded-2xl shadow">
            <ListOfSteps />
            <div className="w-full max-h-[430px] max-w-[450px] mx-auto pt-12 pb-6 text-blue-950">
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </div>
          </main>
        </Suspense>
      </body>
    </html>
  );
}
